/**
 * Dot's voice.
 *
 * Plays the ElevenLabs clips generated by `npm run voices` (listed in
 * audio/voice/manifest.json). Any line that has no clip is spoken by the
 * device's own voice instead, from the same text, so the game never goes
 * silent because a file is missing.
 *
 * Lines are played in sequence — `say('find_real', 'glyph.d5.name')` says
 * "Find the real… five" — and a new request interrupts whatever was playing.
 * Interrupting always settles the interrupted `say()` promise, and every
 * clip has a time limit, so a caller waiting for Dot to finish can never be
 * left hanging (a backgrounded tab, a clip that never fires "ended").
 *
 * On iOS an <audio> element may only start playing inside a user gesture
 * until it has been "unlocked" once, so `unlock()` is called from the first
 * tap on the page. If a play() is refused anyway, the clip falls back to Web
 * Audio through the shared context from sfx.js.
 */

import { phraseText } from '../core/phrases.js';

/** A 50 ms silent WAV, built by hand: the unlock sound nobody hears. */
function silentWav() {
  const rate = 8000;
  const samples = rate / 20;
  const buf = new ArrayBuffer(44 + samples * 2);
  const v = new DataView(buf);
  const str = (o, s) => [...s].forEach((c, i) => v.setUint8(o + i, c.charCodeAt(0)));
  str(0, 'RIFF');
  v.setUint32(4, 36 + samples * 2, true);
  str(8, 'WAVE');
  str(12, 'fmt ');
  v.setUint32(16, 16, true);
  v.setUint16(20, 1, true);
  v.setUint16(22, 1, true);
  v.setUint32(24, rate, true);
  v.setUint32(28, rate * 2, true);
  v.setUint16(32, 2, true);
  v.setUint16(34, 16, true);
  str(36, 'data');
  v.setUint32(40, samples * 2, true);
  let bin = '';
  for (const b of new Uint8Array(buf)) bin += String.fromCharCode(b);
  return `data:audio/wav;base64,${btoa(bin)}`;
}

const CLIP_LIMIT_MS = 15000;

export function createVoice({ base = 'audio/voice/', sfx = null } = {}) {
  let manifest = { clips: {} };
  let enabled = true;
  let unlocked = false;
  let audio = null;
  let generation = 0;
  /** Settles whatever is playing right now; set by each player, called by stop(). */
  let interrupt = null;
  const buffers = new Map();

  async function load() {
    try {
      const res = await fetch(`${base}manifest.json`, { cache: 'no-cache' });
      if (res.ok) manifest = await res.json();
    } catch {
      manifest = { clips: {} };
    }
    manifest.clips ??= {};
    return manifest;
  }

  function unlock() {
    if (unlocked) return;
    unlocked = true;
    audio = new Audio();
    audio.preload = 'auto';
    audio.setAttribute('playsinline', '');
    try {
      audio.src = silentWav();
      audio.play().catch(() => {});
    } catch {
      /* ignore */
    }
    if ('speechSynthesis' in window) {
      // Warm the synthesis engine so the first fallback line is not late.
      try {
        const u = new SpeechSynthesisUtterance('');
        u.volume = 0;
        window.speechSynthesis.speak(u);
      } catch {
        /* ignore */
      }
    }
  }

  const has = (id) => Boolean(manifest.clips[id]);
  const clipUrl = (id) => `${base}${manifest.clips[id].file}`;

  function stop() {
    generation++;
    if (audio) {
      try {
        audio.pause();
      } catch {
        /* ignore */
      }
      audio.onended = null;
      audio.onerror = null;
    }
    try {
      window.speechSynthesis?.cancel();
    } catch {
      /* ignore */
    }
    const settle = interrupt;
    interrupt = null;
    settle?.();
  }

  /**
   * Run one playback. `start(finish)` begins it and calls finish() when it
   * ends or finish(error) when it fails. stop() and the time limit both
   * count as finishing.
   */
  function guarded(start, limitMs) {
    return new Promise((resolve, reject) => {
      let settled = false;
      const finish = (error) => {
        if (settled) return;
        settled = true;
        clearTimeout(timer);
        if (interrupt === finish) interrupt = null;
        if (error) reject(error);
        else resolve();
      };
      const timer = setTimeout(() => finish(), limitMs);
      interrupt = finish;
      try {
        start(finish);
      } catch (error) {
        finish(error);
      }
    });
  }

  const playElement = (url) =>
    guarded((finish) => {
      if (!audio) audio = new Audio();
      audio.onended = () => finish();
      audio.onerror = () => finish(new Error('audio element error'));
      audio.src = url;
      const p = audio.play();
      if (p && p.catch) p.catch((error) => finish(error || new Error('play refused')));
    }, CLIP_LIMIT_MS);

  async function playBuffer(url) {
    const ctx = sfx?.context;
    if (!ctx) throw new Error('no audio context');
    let buffer = buffers.get(url);
    if (!buffer) {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`clip ${res.status}`);
      buffer = await ctx.decodeAudioData(await res.arrayBuffer());
      buffers.set(url, buffer);
    }
    let source = null;
    await guarded((finish) => {
      source = ctx.createBufferSource();
      source.buffer = buffer;
      source.connect(ctx.destination);
      source.onended = () => finish();
      source.start();
    }, buffer.duration * 1000 + 800).finally(() => {
      try {
        source?.stop();
      } catch {
        /* already stopped */
      }
    });
  }

  const speakText = (text) =>
    guarded((finish) => {
      if (!('speechSynthesis' in window)) return finish();
      const u = new SpeechSynthesisUtterance(text);
      u.rate = 0.95;
      u.pitch = 1.05;
      const voices = window.speechSynthesis.getVoices();
      const pick =
        voices.find((v) => /samantha/i.test(v.name)) ||
        voices.find((v) => v.lang === 'en-US' && /female|karen|moira|tessa|ava/i.test(v.name)) ||
        voices.find((v) => v.lang?.startsWith('en'));
      if (pick) u.voice = pick;
      u.onend = () => finish();
      u.onerror = () => finish();
      window.speechSynthesis.speak(u);
    }, text.length * 80 + 2500);

  async function playOne(id, gen) {
    const text = phraseText(id) ?? manifest.clips[id]?.text ?? id;
    if (has(id)) {
      const url = clipUrl(id);
      try {
        await playElement(url);
        return;
      } catch {
        if (gen !== generation) return;
      }
      try {
        await playBuffer(url);
        return;
      } catch {
        if (gen !== generation) return;
      }
    }
    await speakText(text);
  }

  /** Play phrase ids in order. Resolves when finished or interrupted. */
  async function say(...ids) {
    if (!enabled || !ids.length) return;
    stop();
    const gen = generation;
    for (let i = 0; i < ids.length; i++) {
      if (gen !== generation) return;
      const id = ids[i];
      if (!id) continue;
      await playOne(id, gen);
      if (gen !== generation) return;
      if (i < ids.length - 1) await new Promise((r) => setTimeout(r, 90));
    }
  }

  return {
    load,
    unlock,
    say,
    stop,
    has,
    get enabled() {
      return enabled;
    },
    setEnabled(on) {
      enabled = Boolean(on);
      if (!enabled) stop();
    },
    get clipCount() {
      return Object.keys(manifest.clips).length;
    },
    get manifest() {
      return manifest;
    },
  };
}
