/**
 * Dot's voice.
 *
 * Plays the ElevenLabs clips generated by `npm run voices` (listed in
 * audio/voice/manifest.json). Any line that has no clip is spoken by the
 * device's own voice instead, from the same text, so the game never goes
 * silent because a file is missing.
 *
 * Lines are played in sequence — `say('find_real', 'glyph.d5.name')` says
 * "Find the real… five" — and a new request interrupts whatever was playing,
 * so the child never has to wait for Dot to finish a sentence she has moved
 * on from.
 *
 * On iOS an <audio> element may only start playing inside a user gesture
 * until it has been "unlocked" once, so `unlock()` is called from the first
 * tap on the page. If a play() is refused anyway, the clip falls back to Web
 * Audio through the shared context from sfx.js.
 */

import { phraseText } from '../core/phrases.js';

const SILENT_MP3 =
  'data:audio/mpeg;base64,SUQzBAAAAAAAI1RTU0UAAAAPAAADTGF2ZjU4Ljc2LjEwMAAAAAAAAAAAAAAA//tQAAAAAAAAAAAAAAAAAAAAAAAAWGluZwAAAA8AAAACAAABhgC7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7u7//////////////////////////////////////////////////////////////////8AAAAATGF2YzU4LjEzAAAAAAAAAAAAAAAAJAAAAAAAAAAAAYYyR0NQAAAAAAAAAAAAAAAAAAAAAP/7EGQAAAKgAAA0AAAAABACAAAAABIAAAAAAAAAAAAAAAAAAAExhdmM1OC4xMwAAAAAAAAAAAAAAACQAAAAAAAAAAAGGMkdDUAAAAAAAAAAAAAAAAAAAAAD/+xBkAAACoAAANAAAAAAQAgAAAAASAAAAAAAAAAAAAAAAAAAB';

export function createVoice({ base = 'audio/voice/', sfx = null } = {}) {
  let manifest = { clips: {} };
  let enabled = true;
  let unlocked = false;
  let audio = null;
  let generation = 0;
  const buffers = new Map();

  async function load() {
    try {
      const res = await fetch(`${base}manifest.json`, { cache: 'no-cache' });
      if (res.ok) manifest = await res.json();
    } catch {
      manifest = { clips: {} };
    }
    manifest.clips ??= {};
    return manifest;
  }

  function unlock() {
    if (unlocked) return;
    unlocked = true;
    audio = new Audio();
    audio.preload = 'auto';
    audio.setAttribute('playsinline', '');
    audio.src = SILENT_MP3;
    audio.play().catch(() => {});
    if ('speechSynthesis' in window) {
      // Warm the synthesis engine so the first fallback line is not late.
      try {
        const u = new SpeechSynthesisUtterance('');
        u.volume = 0;
        window.speechSynthesis.speak(u);
      } catch {
        /* ignore */
      }
    }
  }

  const has = (id) => Boolean(manifest.clips[id]);
  const clipUrl = (id) => `${base}${manifest.clips[id].file}`;

  function stop() {
    generation++;
    if (audio) {
      audio.pause();
      audio.onended = null;
      audio.onerror = null;
    }
    try {
      window.speechSynthesis?.cancel();
    } catch {
      /* ignore */
    }
  }

  function playElement(url) {
    return new Promise((resolve, reject) => {
      if (!audio) audio = new Audio();
      audio.onended = () => resolve();
      audio.onerror = () => reject(new Error('audio element error'));
      audio.src = url;
      audio.currentTime = 0;
      const p = audio.play();
      if (p && p.catch) p.catch(reject);
    });
  }

  async function playBuffer(url) {
    const ctx = sfx?.context;
    if (!ctx) throw new Error('no audio context');
    let buffer = buffers.get(url);
    if (!buffer) {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`clip ${res.status}`);
      buffer = await ctx.decodeAudioData(await res.arrayBuffer());
      buffers.set(url, buffer);
    }
    await new Promise((resolve) => {
      const src = ctx.createBufferSource();
      src.buffer = buffer;
      src.connect(ctx.destination);
      src.onended = resolve;
      src.start();
    });
  }

  function speakText(text) {
    return new Promise((resolve) => {
      if (!('speechSynthesis' in window)) return resolve();
      const u = new SpeechSynthesisUtterance(text);
      u.rate = 0.95;
      u.pitch = 1.05;
      const voices = window.speechSynthesis.getVoices();
      const pick =
        voices.find((v) => /samantha/i.test(v.name)) ||
        voices.find((v) => v.lang === 'en-US' && /female|karen|moira|tessa|ava/i.test(v.name)) ||
        voices.find((v) => v.lang?.startsWith('en'));
      if (pick) u.voice = pick;
      u.onend = resolve;
      u.onerror = resolve;
      window.speechSynthesis.speak(u);
    });
  }

  async function playOne(id, gen) {
    const text = phraseText(id) ?? manifest.clips[id]?.text ?? id;
    if (has(id)) {
      const url = clipUrl(id);
      try {
        await playElement(url);
        return;
      } catch {
        if (gen !== generation) return;
      }
      try {
        await playBuffer(url);
        return;
      } catch {
        if (gen !== generation) return;
      }
    }
    await speakText(text);
  }

  /** Play phrase ids in order. Resolves when finished or interrupted. */
  async function say(...ids) {
    if (!enabled || !ids.length) return;
    stop();
    const gen = generation;
    for (let i = 0; i < ids.length; i++) {
      if (gen !== generation) return;
      const id = ids[i];
      if (!id) continue;
      await playOne(id, gen);
      if (i < ids.length - 1) await new Promise((r) => setTimeout(r, 90));
    }
  }

  return {
    load,
    unlock,
    say,
    stop,
    has,
    get enabled() {
      return enabled;
    },
    setEnabled(on) {
      enabled = Boolean(on);
      if (!enabled) stop();
    },
    get clipCount() {
      return Object.keys(manifest.clips).length;
    },
    get manifest() {
      return manifest;
    },
  };
}
